apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: freestyle-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: freestyle-secrets
  data:
    - secretKey: INFLUXDB_HOST
      remoteRef:
        key: INFLUXDB_HOST
    - secretKey: INFLUXDB_PORT
      remoteRef:
        key: INFLUXDB_PORT
    - secretKey: INFLUXDB_USERNAME
      remoteRef:
        key: INFLUXDB_ADMIN_USER
    - secretKey: INFLUXDB_PASSWORD
      remoteRef:
        key: INFLUXDB_ADMIN_PASSWORD
    - secretKey: LIBRELINKUP_USERNAME
      remoteRef:
        key: LIBRELINKUP_USERNAME
    - secretKey: LIBRELINKUP_PASSWORD
      remoteRef:
        key: LIBRELINKUP_PASSWORD
    - secretKey: LIBRELINKUP_DATABASE
      remoteRef:
        key: LIBRELINKUP_DATABASE